# Generated by Django 5.2.2 on 2025-06-05 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habito',
            name='data_conclusao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
