# Generated by Django 5.2.2 on 2025-06-05 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitos', '0002_habito_data_conclusao'),
    ]

    operations = [
        migrations.AddField(
            model_name='habito',
            name='streak',
            field=models.IntegerField(default=0),
        ),
    ]
