# Generated by Django 5.2.2 on 2025-06-06 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitos', '0003_habito_streak'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streak', models.IntegerField(default=0)),
                ('percentual_conclusao_mes', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='habito',
            name='streak',
        ),
    ]
